runtime: python37

handlers:
- url: /(.*\.css)$
  static_files: \1
  upload: style.css

- url: /(.*\.html)$
  static_files: \1
  upload: index.html

- url: /(.*)
  static_files: index.html
  upload: index.html
